version: '3.7'

services:
  gitlab-web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-web
    hostname: gitlab-web
    volumes:
      - './gitlab-config:/etc/gitlab'
      - './gitlab-logs:/var/log/gitlab'
      - './gitlab-data:/var/opt/gitlab'
    ports:
      - '2222:22'
      - '8081:80'
      - '4443:443'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://localhost:4567'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:
      gitlab-network:
        ipv4_address: 172.21.0.3
        aliases:
          - gitlab-web

  postgresql:
    image: postgres:latest

    environment:
      POSTGRES_DB: lugar-db
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
     # - './gitlab-runner1-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      gitlab-network:
        ipv4_address: 172.21.0.2
        aliases:
          - gitlab-runner1


networks:
  gitlab-network:
    driver: bridge

    ipam:
      config:
        - subnet: 172.21.0.0/24

