version: '3.7'

services:
  gitlab-web:
    image: 192.168.1.11:5000/gitlab/gitlab-ce
    container_name: gitlab-web
    hostname: gitlab-web
    volumes:
      - './gitlab-config:/etc/gitlab'
      - './gitlab-logs:/var/log/gitlab'
      - './gitlab-data:/var/opt/gitlab'
    ports:
      - '2222:22'
      - '8081:81'
      - '4443:443'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://localhost:4567'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:

      net_backend:
        ipv4_address: 172.21.0.19

  #Le service MySQL
  mysql-server:
    image:  192.168.1.11:5000/mysql
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    #   - --require-secure-transport
    #   - --ssl-ca=/run/secrets/root-ca.pem
    #   - --ssl-cert=/run/secrets/server-cert.pem
    #   - --ssl-key=/run/secrets/server-key.pem
    volumes:
      - "./mysql-data/var/lib/mysql:/var/lib/mysql:rw"
    env_file:
      - .env_mysql
    container_name: mysql-server
    #secrets:
    #   - server-key.pem
    #   - server-cert.pem
    #   - root-ca.pem
    #  stop_grace_period: 1m
    networks:
      net_backend:
        ipv4_address: 172.21.0.11
        aliases:
          - mysql-server
    tty: true
    #Cette ligne permet de résoudre le probleme de mbind: Operation not permitted
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped

  phpmyadmin:
    image: 192.168.1.11:5000/phpmyadmin/phpmyadmin
    ports:
      - "8084:80"
    container_name: phpmyadmin
    env_file:
      - .env_mysql
    restart: unless-stopped
    tty: true
    links:
      - "mysql-server"
    volumes:
      - "./phpmyadmin/session:/sessions"
      #- "./phpmyadmin/php_ini:/usr/local/etc/php"
      #- "./phpmyadmin/apache2_config:/etc/apache2"
    networks:

      net_backend:
        ipv4_address: 172.21.0.17
        aliases:
          - phpmyadmin
    environment:
      PMA_HOST: "mysql-server" # mysql-server

  gitlab-runner1:
    image: 192.168.1.11:5000/gitlab-runner
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
     # - './gitlab-runner1-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:

      net_backend:
        ipv4_address: 172.21.0.2

networks:

  net_backend:
    driver: bridge
    #internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/24